spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/referral_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: Nika Referral System

server:
  port: 8080
